### ISSUE TITLE
Adding TrenchBroom Group support

### ISSUE THREAD

**Issue by yochrisbolton** [codecat/godot-tbloader#1]
Hello,

I appreciate you creating this. I've been experimenting with Godot 4 and its nice to see a quake map compiler already working on 4

One thing I noticed when exporting some maps is that it appears that `Groups` in TrenchBroom don't compile inside of Godot, is this a planned feature on the roadmap? 

Cheers,

**Comment by codecat** [comment]
Looks like groups are just separate worldspawn-type entities with the class name `func_group`, this can definitely be added. I'll see about implementing this later today 👍

**Comment by codecat** [comment]
I've added partial support for this. I still have to make it so that separate worldspawn entities are merged into 1 though.

**Comment by codecat** [comment]
Actually, it might be nicer, Godot-wise, to just separate layers and groups as separate nodes anyway 😄

**Comment by yochrisbolton** [comment]
That is fantastic, thank you for your quick response and updates here! 

Appreciate what you're doing here with the project 🍻

**Comment by codecat** [comment]
Just noticed your sponsor donation, thank you so much!
