### ISSUE TITLE
Some game configurations could not be loaded.

### ISSUE THREAD

**Issue by seacat17** [codecat/godot-tbloader#104]
When copying files from tb-gameconfig into games/Godot/ directory - I get this error when launching TrenchBroom.

```
Some game configurations could not be loaded. The following errors occurred:

Failed to load game configuration file 'Godot/GameConfig.cfg': At line 2, column 14:  Unsupported game configuration version 4; valid versions are: 7, 8
```

**Comment by codecat** [comment]
Is this on the latest git version, or on the release on Godot Assets?

**Comment by seacat17** [comment]
> Is this on the latest git version, or on the release on Godot Assets?

It's from AssetLib

**Comment by seacat17** [comment]
Is there any way to solve this? GameJam is coming...

**Comment by seacat17** [comment]
The issue was solved by compiling the software from source.

**Comment by codecat** [comment]
Indeed. I am doing 7DFPS myself as well, so will look into publishing the latest version of this on AssetLib today 😊

**Comment by seacat17** [comment]
> Indeed. I am doing 7DFPS myself as well, so will look into publishing the latest version of this on AssetLib today 😊

I... Left it.
