### ISSUE TITLE
Linux binary not included in the asset store download

### ISSUE THREAD

**Issue by theangrygrunt** [codecat/godot-tbloader#11]
I did try to compile it myself but I got these error messages 

```
scons: Reading SConscript files ...

scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
Missing SConscript 'godot-cpp/SConstruct'
File "/home/grunt/github/peregrine/addons/godot-tbloader/SConstruct", line 5, in <module>
AttributeError: 'NoneType' object has no attribute 'Append':
  File "/home/grunt/github/peregrine/addons/godot-tbloader/SConstruct", line 16:
    env.Append(CPPPATH=["src/", "src/map/"])
```

Any chance that a Linux binary will be available? I really would like to use Trenchboom as a level builder for Godot.

**Comment by kherchel** [comment]
@theangrygrunt 

Had the same thing happen and just figured it out.
You have to run `git submodule update --init --recursive` before `scons` to get the godot-cpp dependency.

**Comment by theangrygrunt** [comment]
I'll try that later this week, ty!

**Comment by codecat** [comment]
When I get some time I'll see if I can get it compiled for Linux as well. I'm primarily a Windows developer so I need to find a good way to automate Linux builds 😅

Could maybe do it through WSL or something.

**Comment by jgillich** [comment]
GitHub Actions is a great way to automate builds for all platforms :wink:

**Comment by codecat** [comment]
I have added a Linux & MacOS Universal binary to the asset store version. It is pending approval by moderators, but you can download it here: https://github.com/codecat/godot-tbloader/releases/tag/v0.1.1

Let me know if it works!

**Comment by codecat** [comment]
The assetlib update has been approved now. If anyone can test this on Linux (and Mac potentially) let me know!

**Comment by codecat** [comment]
Will assume this works. Gonna close for now. Feel free to open a new issue if there are any problems with the build.
