### ISSUE TITLE
Godot 4 alpha 13 install issue

### ISSUE THREAD

**Issue by nickpolet** [codecat/godot-tbloader#13]
Just trying to load this addon from AssetLib, and getting this error. Looks like the binary maybe isn't included when installing this way.

```
Can't open dynamic library: /path/to/project/addons/tbloader/bin/libtbloader.linux.x86_64.so. Error: /path/to/project/editor/../lib/libtbloader.linux.x86_64.so: cannot open shared object file: No such file or directory
  core/extension/native_extension.cpp:266 - GDExtension dynamic library not found: /path/to/project/addons/tbloader/bin/libtbloader.linux.x86_64.so
  Failed loading resource: res://addons/tbloader/tbloader.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

```

I think there might be a few other issues created relating to a similar thing here. Might be good to include some build instructions in the readme if it's easier to have people build the project on their own platform.

**Comment by codecat** [comment]
Yeah this is a duplicate of #11. Sorry about that, I'll work on fixing this soon!

**Comment by nickpolet** [comment]
Yep sorry for the duplicate. Looking forward to using it. Loved Qodot... excited for this!

**Comment by codecat** [comment]
0.1.1 should be live and approved on assetlib now, let me know if this resolves your issue! (I haven't been able to test this myself yet 😳)
