### ISSUE TITLE
Document how to use tbloader

### ISSUE THREAD

**Issue by fire** [codecat/godot-tbloader#17]
1. scoop install trenchbroom
2. install alpha 14 https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-14
3. Place the  tb-gameconfig folder in a folder called Godot inside the games folder of your TrenchBroom installation, so you would have games/Godot/<files>.
3. ???
4. Loaded map in editor

**Comment by codecat** [comment]
True, there should be better documentation for this. I would probably primarily point to installing through AssetLib.

**Comment by fire** [comment]
I cannot find the AssetLib entry for tbloader.

https://godotengine.org/asset-library/asset?category=&godot_version=&sort=updated&filter=tbloader

**Comment by codecat** [comment]
It's actually listed as "TrenchBroom Loader" there. Not sure if it can show up as "TBLoader" too.

**Comment by codecat** [comment]
Additionally, I kinda want an easier install method for TrenchBroom itself, perhaps something based on #4 that automatically generates the entire game configuration with a little wizard inside of Godot.

**Comment by fire** [comment]
Add the "TBLoader" keyword to the text.

**Comment by codecat** [comment]
I'm not sure that works. "Qodot" is also a term in the asset description, but it doesn't show up when you search "Qodot". Perhaps this is something that will be improved once [the new version of asset lib](https://github.com/Calinou/godot-asset-library-laravel) is deployed?

**Comment by MortimerMcMire** [comment]
Any update on this? It looks like a working qodot alternative for 4.0 but I have no idea what I'm supposed to be doing. A 3 minute video, some screenshots, or even a few sentences would go a long way

**Comment by codecat** [comment]
I have updated the readme with some basic usage instructions. Hopefully this is sufficient for the basic usage.

**Comment by fire** [comment]
Yay! Open a new ticket if there are more questions.
