### ISSUE TITLE
Unwrap UV2

### ISSUE THREAD

**Issue by gildedhipbone** [codecat/godot-tbloader#3]
I have issues baking lightmaps due to the generated meshes not being unwrapped for UV2. It's possible to let Godot do the unwrapping; it does this only for currently selected MeshInstances via "Unwrap UV2 for LightMap/AO" in the "Mesh" popup menu:
![image](https://user-images.githubusercontent.com/36510916/156904808-2ac11273-b347-4fce-b927-8fe4aadd7a68.png)
The unwrapping code isn't exposed to the scripting API, as far as I know. While it's not a huge hassle to find and select all the MeshInstances via script and then click "Unwrap UV2 for LightMap/AO", it gets old. I think it'd be nice to have 1) a "Unwrap UV2" button that gets and unwraps all the generated MeshInstances, and 2) an option for automatic unwrapping.
![image](https://user-images.githubusercontent.com/36510916/156904646-0c72d4b3-78d0-451f-9d6b-1eec9159d415.png)

**Comment by codecat** [comment]
I have added an option to TBLoader to do this automatically when building:

![image](https://user-images.githubusercontent.com/136534/156923915-2e8eec97-71c7-4d15-9d4a-3d3ea75ce711.png)

Maybe it makes sense to put it in the toolbar too, though?

**Comment by gildedhipbone** [comment]
Nice! That's wonderful.

No, I think you got it right. It makes sense that the auto unwrap setting belongs in TBLoader. And for those odd cases where you'd want to unwrap UV2 only for a specific MeshInstance you can still use the ol' manual "Unwrap UV2 for LightMap/AO".

Does TBLoader set GI Mode to static for all MeshInstances? I think it's reasonable that GI Mode have default values, like Static for structural brushes or Dynamic for door_func (and other moving entities which will probably use AnimatableBody3D), it should be possible for users to manually set the GI Mode on a brush/entity basis. Thinking about it,

**Comment by codecat** [comment]
Yes, currently every mesh instance is set to static. Brush entities could have a property to override this inside of TrenchBroom to set this to none or dynamic.

Feel free to make a separate issue for that so I don't forget!
