### ISSUE TITLE
Crash on open with Godot 4.0.beta2

### ISSUE THREAD

**Issue by Syntaxxor** [codecat/godot-tbloader#30]
Godot 4.0.beta2 has come out, and it seems that it's incompatible with this version of tbloader. I'm mostly posting this just to make sure that you're aware of that and can update it when you get the chance.

**Comment by codecat** [comment]
Thanks for the ping! I will do an update release soon.

**Comment by codecat** [comment]
The update is released on Github now! It's also pushed to assetlib, whenever the moderators get around to approving the change. 👍
