### ISSUE TITLE
Doesn't seem to work on Linux

### ISSUE THREAD

**Issue by dmitsuki** [codecat/godot-tbloader#34]
After installing tbloader on Linux it doesn't seem to work. It installs, but the node doesn't have the tbloader icon and when creating the node you have no options to build it or anything.

**Comment by codecat** [comment]
I don't have a good way of testing this myself now (no proper Linux boot) so I will have to take a look at this when I get that set up 👀

**Comment by dmitsuki** [comment]
I'm very new to Godot. I think the buttons are created in plugin.gd but how would I go about debugging them?

**Comment by codecat** [comment]
Great! Thanks for letting me know 👷‍♀️
