### ISSUE TITLE
new dependency on version 0.4.0? - ucrtbased.dll

### ISSUE THREAD

**Issue by Bacco** [codecat/godot-tbloader#36]
Couldn't port a project from 0.3.0 to 0.4.0:

> tb_loader.tscn - G 4 Trench Broom Test 001 - Godot Engine: Godot_v4.0-beta4_win64.exe - System Error
> The program can't start because ucrtbased.dll is missing from your computer. Try reinstalling the program to fix this problem. 

Did a quick search, it seems an win 10 dependency. If it's the case, I suggest recompiling with 7 in mind. 

_(And if it's really the case, I suggest people don't bring "no one should be using 7" into focus, so the issue keeps technical. I still want to support 7 users, don't believe a game should force anyone to upgrade - Godot itself is working very well on 7)._

**Comment by codecat** [comment]
`ucrtbased.dll` is a debug dll, which means it is linking to the debug runtime for some reason. I am not sure why this is happening. Perhaps there is a bug in https://github.com/godotengine/godot-cpp/pull/867?

**Comment by Bacco** [comment]
I did some tests here with 4b4, it happened only in one project with a TBLoader node. I'll do more tests anyway and update here if I find any clue.

**Comment by codecat** [comment]
I mean I can confirm that the TBLoader dll has linked to the debug runtime. The thing I'm confused about is *why* it happens. 😅

**Comment by Bacco** [comment]
Alas, thanks for the quick reply (and TBLoader itself of course). Sorry for the poor issue report. I'm a little "divided" here with other non-godot issues, it's just that I opted for "at least report something" than not reporting at all. Hope I can give more useful feedback in the future.

**Comment by codecat** [comment]
No worries at all, this is a perfectly valid issue and a perfectly valid report! Thanks for reporting it 😸

**Comment by codecat** [comment]
I have a workaround for this and will release 0.4.1 later today!

**Comment by codecat** [comment]
This is fixed in 0.4.1: https://github.com/codecat/godot-tbloader/releases/tag/v0.4.1

**Comment by Bacco** [comment]
Tested on win 7, working nicely. thank you very much.
