### ISSUE TITLE
Add an option to customize the path for textures

### ISSUE THREAD

**Issue by monkey-salad** [codecat/godot-tbloader#41]
TBLoader currently enforces a certain path for textures (`"res://textures"`), which hurts project organization.

It's already possible to customize the path for _entities_ on the `TBLoader` node, why not have this option for textures too?

**Comment by Levrault** [comment]
hi @codecat I think this issue can be closed with PR https://github.com/codecat/godot-tbloader/pull/44

**Comment by codecat** [comment]
You're right! Forgot to do that 👍
