### ISSUE TITLE
Godot 4.0 beta 5 incompatability

### ISSUE THREAD

**Issue by grynmoor** [codecat/godot-tbloader#42]
Hello!

As the title suggests, TBLoader causes Godot to crash on startup in the newest 4.0 beta.
I'm looking forward to a fix. Your work is awesome 🙏

**Comment by codecat** [comment]
Oops, thanks for letting me know! I will fix this in the morning 🥰

**Comment by codecat** [comment]
This should be fixed now with 0.5.0: https://github.com/codecat/godot-tbloader/releases

Asset library update is currently pending for review and will also be available soon 👍
