### ISSUE TITLE
Mesh normals aren't normalized when building

### ISSUE THREAD

**Issue by Yagich** [codecat/godot-tbloader#43]
I was working on bullet hole decals for weapons, when I noticed an issue. The decals (with normal fade set to 0.99) would show up on 90-degree surfaces, but wouldn't on slopes. Writing a simple shader to normalize normals in the vertex pass and putting it on the geometry fixed the problem, but doing a simple shader with an albedo texture and the normal fix for every single texture in my game sounds overkill.
In theory, this could also negatively affect lighting, but I haven't noticed anything wrong.

**Comment by codecat** [comment]
Interesting, maybe @EIREXE has an idea?

**Comment by EIREXE** [comment]
I just ran some checks and mesh normals are normalized correctly, the issue doesn't appear to be in godot-tbloader
 
![image](https://user-images.githubusercontent.com/3101690/202974845-8c5af617-e108-4fdf-8299-119d0c29619c.png)

**Comment by Yagich** [comment]
Interesting. I'll do some checks on my end tomorrow.

**Comment by Yagich** [comment]
I tested it again on a blank project. On the left is a TBLoader map with an unshaded material and a Decal on a ramp with `normal_fade` set to 0.5. On the right is the same map and Decal, but the material has a shader whose vertex function has `NORMAL = normalize(NORMAL)`. So I'm not sure why you don't have the issue @EIREXE 🤔
![image](https://user-images.githubusercontent.com/24468819/203239256-8d3ec3ca-cf4c-4448-9afe-c6de3e738eb1.png)

**Comment by EIREXE** [comment]
> I tested it again on a blank project. On the left is a TBLoader map with an unshaded material and a Decal pointed 45 degrees up on a ramp with `normal_fade` set to 0.5. On the right is the same map and Decal, but the material has a shader whose vertex function has `NORMAL = normalize(NORMAL)`. So I'm not sure why you don't have the issue @EIREXE thinking ![image](https://user-images.githubusercontent.com/24468819/203239256-8d3ec3ca-cf4c-4448-9afe-c6de3e738eb1.png)

you can do:

```
for normal in mesh.surface_get_arrays(0)[Mesh.ARRAY_NORMAL]:
	prints(normal, normal.normalized())
```

And compare, I am using latest master and I don't see any problem

**Comment by Yagich** [comment]
Very strange. They are the same, you're right. But the decal still looks faded, even though it's aligned. I put a BoxMesh next to the ramp from TB: 
![image](https://user-images.githubusercontent.com/24468819/203423902-a0df9624-0511-43a1-aade-1a99415d578b.png)
I wonder if it's a Decal issue.

**Comment by codecat** [comment]
I am not too familiar with decals. Do you think this is still an issue in TBLoader or not?

**Comment by Yagich** [comment]
Just checked the latest version and it doesn't seem to happen now. Sorry for the waste of time.

**Comment by codecat** [comment]
No worries, thanks for letting me know 😊
