### ISSUE TITLE
Godot 4 Beta 7 crash

### ISSUE THREAD

**Issue by CptnRoughnight** [codecat/godot-tbloader#46]
OS : Windows 10
Godot 4 Beta 7 Mono 

Building map inside Godot crashes with "ERROR: Hash mismatch for method 'Mesh.create_trimesh_shape'."

Testproject :
[trenchtest.zip](https://github.com/codecat/godot-tbloader/files/10140865/trenchtest.zip)

**Comment by CptnRoughnight** [comment]
Just tested with Godot 4 Beta 6 Mono version ... no crash

**Comment by codecat** [comment]
I'll fix this, thanks!
