### ISSUE TITLE
Properties on brush entities from trenchbroom?

### ISSUE THREAD

**Issue by elvisish** [codecat/godot-tbloader#48]
Is there a way of getting properties on brush entities in trenchbroom to import in TBLoader? I've tried as the readme suggests with export variables on my entity tscn but nothing seems to work?

**Comment by codecat** [comment]
Debugged this a bit over Discord. The problem was forgetting to assign a default value to the property. For example:
```
# This works
@export var thing: int = 0

# This does not
@export var thing: int
```
