### ISSUE TITLE
Missing transform when dll isn't shipped with exported game

### ISSUE THREAD

**Issue by codecat** [codecat/godot-tbloader#5]
When exported, the TBLoader node turns into a Node rather than a Node3D (because the dll is not loaded), meaning any transform on the node will be lost.

**Comment by gildedhipbone** [comment]
Is this something inherent to GDExtensions?

**Comment by codecat** [comment]
This is because `TBLoader` is a C++ node inheriting from `Node3D`, and when the dll is not loaded (eg. it's not bundled with the game's exported exe) it doesn't know what the node originally was and turns it into a `Node` instead.

The simple solution is to ship the dll with the exported exe, but I'm wondering if there might be a better solution.
