### ISSUE TITLE
Crash on map build with Godot 4.0 beta 11 when using Linux

### ISSUE THREAD

**Issue by ShadowFungi** [codecat/godot-tbloader#58]
I've been rewriting a project of mine in Godot 4.0 using TrenchBroom and godot-tbloader, it was going well until today when I updated to Godot 4.0 beta 11, in which whenever I try to build the meshes any map that contains geometry Godot will crash, when run in the terminal it provides the following error
```
Building map res://assets/models/maps/test.map
ERROR: Hash mismatch for method 'ArrayMesh.add_surface_from_arrays'.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:912)
```
when building a map in Godot 4.0 beta 10 there is no such error.
I've attached an archive of a Godot project I reproduced the error in provided in the archive are a simple TrenchBroom map, and a Godot scene where the map can be built. I would be glad to test if it can be reproduced on other operating systems tomorrow.
[test.zip](https://github.com/codecat/godot-tbloader/files/10387788/test.zip)

**Comment by codecat** [comment]
Thanks! This should be fixed in 0.11.0, available on Github releases now and the asset library after review.

**Comment by krazyjakee** [comment]
I may be too quick here but the release appears to contain different code to the master branch. Has it been pushed?

**Comment by codecat** [comment]
Oh, you mean the "build combined CSG" button - indeed, that was removed on the master branch, but not on the assetlib version yet, so that code is indeed different 😅

I'm still unsure how I want to do it. I think your PR should probably revert the most recent comment that adds back the CSG button.
