### ISSUE TITLE
Trench broom Loader crashes Godot Alpha 5

### ISSUE THREAD

**Issue by HeadClot** [codecat/godot-tbloader#6]
Hey, 
I have been working with this tool in Godot 4 alpha 4 for a bit now and I really like it. However when I try to load it in [Godot 4 alpha 5](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-5) it crashes Godot Engine. As long as Trench broom loader is in the addon directory it refuses to open the project. However If I take it out It or delete Trench broom loader from the addon directory it allows me to open the project.

I am not sure where the log files are but I am willing to get them to you if I can find them.

**Comment by codecat** [comment]
Ah, didn't realize Alpha 5 was out. I'll update it today!

**Comment by HeadClot** [comment]
> Ah, didn't realize Alpha 5 was out. I'll update it today!

Thank you. :)

**Comment by codecat** [comment]
I updated this and a new release is available here: https://github.com/codecat/godot-tbloader/releases

The updated version on the [Asset Library](https://godotengine.org/asset-library/asset/1265) is currently pending moderator approval.
