### ISSUE TITLE
Crashes on Latest godot 4 (RC1)

### ISSUE THREAD

**Issue by mrjshzk** [codecat/godot-tbloader#65]
When adding the release build or the source zip addon folder the engine crashes and only can open again once you remove the plugin files entirely

**Comment by codecat** [comment]
Oh I didn't realize there was an RC release now!! That's exciting. I'll make sure I have an update for this.

**Comment by mrjshzk** [comment]
Yeah, good stuff coming up. It's weird tho, the plugin gdscript seemingly has a syntax error on the handles function

**Comment by codecat** [comment]
Oh? It seemed to work okay for me. What's the error?

**Comment by mrjshzk** [comment]
Unfortunately I can't even check it becaus just having the plugin addon folder in the project makes it instantaneously crash

**Comment by mrjshzk** [comment]
Can you use the plugin normally yourself?

**Comment by codecat** [comment]
Are you using 0.15.0 that was just released? https://github.com/codecat/godot-tbloader/releases/tag/v0.15.0

**Comment by mrjshzk** [comment]
Wait a sec

**Comment by mrjshzk** [comment]
It works!!!!! :))))))
