### ISSUE TITLE
Mesh created without textures when building with godot-cpp for rc2

### ISSUE THREAD

**Issue by dominiks** [codecat/godot-tbloader#68]
Hi, after successfully using this addon for a while I now encounter a problem when recreating the meshes from maps. When I create an example map like this:

![trenchbroom_screenshot](https://user-images.githubusercontent.com/109005/218998372-c125eca4-f2bc-43cb-bca9-d1c04e72a606.png)

Creating the mesh with the plugin results in this:

![generated_mesh](https://user-images.githubusercontent.com/109005/218998524-5d1d0a4a-55e4-42bc-aa87-9b7b4ee1cc7f.png)

Apparently the mesh does not have any materials set.
![mesh_properties](https://user-images.githubusercontent.com/109005/218998607-4e1c349e-4308-4071-9d89-1c5ead4452d6.png)

When changing the `texture_path` of the TBLoader node to something wrong, I get the expected error message `Texture cannot be found or is unsupported! - res://prototype_textures/128/green_checker`.

I am using a custom build with `precision=double` based on Godot 4 Rc2. The `green_checker.png` file is automatically imported as `Texture2D`.

**Comment by dominiks** [comment]
After playing around with different combinations of custom builds and releases I found that it works correctly when I build tbloader with godot-cpp checked out at https://github.com/godotengine/godot-cpp/commit/516fad14e45d341211121832bb3daa172aebd6e1 (synced with RC1) and not when checked out at https://github.com/godotengine/godot-cpp/commit/0068320ff13fd91d16f3a2bdcf7956cd439c2869 (sycned with RC2).

**Comment by codecat** [comment]
That's interesting, are there no compiler errors? It kinda sounds like this might be a bug in godot-cpp then, maybe? 🤔

**Comment by mrjshzk** [comment]
Hello, have you tried renaming your texture folder to 'textures'?

**Comment by codecat** [comment]
Looks to be caused by this change: https://github.com/godotengine/godot-cpp/commit/75af9003dc2b1583966ab91be6ce1687378860ae

**Comment by codecat** [comment]
The latest godot-cpp commit should fix this.

**Comment by dominiks** [comment]
Great to hear. Thank you for taking the time to investigate this.
