### ISSUE TITLE
Unable to create collider shape from mesh!

### ISSUE THREAD

**Issue by mrjshzk** [codecat/godot-tbloader#69]
Hello! When trying to build, it gives me this error 'Unable to create collider shape from mesh!'
The plugin was working fine, i dont know why this happened.

![imagem](https://user-images.githubusercontent.com/115943663/219492653-71af9ffd-e739-4fd9-a211-ec6abfb5fdfe.png)

**Comment by codecat** [comment]
Hmm this means that `create_convex_shape` or `create_trimesh_shape` is returning null. The documentation isn't very clear on the cases when this could happen. Do you know which meshes it is talking about? Perhaps it's an empty mesh?

**Comment by mrjshzk** [comment]
How can I get that information?

**Comment by codecat** [comment]
Okay I just did some testing, and this might be related to #68 as well, are you on RC2? I'm able to reproduce this on Godot 4 RC2. It seems like the resource loader is failing to load any resources. I'm looking into it!

**Comment by mrjshzk** [comment]
Yes! I am on RC2

**Comment by codecat** [comment]
Looks to be caused by this change: https://github.com/godotengine/godot-cpp/commit/75af9003dc2b1583966ab91be6ce1687378860ae

**Comment by codecat** [comment]
The latest godot-cpp commit should fix this.

**Comment by mrjshzk** [comment]
Thank you! I'll wait for the next release as I'm too lazy to compile the engine :p
