### ISSUE TITLE
Doesn't work with godot 4.1

### ISSUE THREAD

**Issue by cuppajoeman** [codecat/godot-tbloader#81]
On godot 4.1, downloading a zip of the master branch and adding it to a fresh godot project I get:

![image](https://github.com/codecat/godot-tbloader/assets/19198104/396cdb79-c5e5-45cd-a476-3b8100887a0b)

Getting past that dialog and attempting to enable the plugin through the settings, we get the following error: 

```
Unable to load addon script from path: 'res://addons/tbloader/src/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/tbloader/plugin.cfg' to prevent further errors.
```

taking a look in `plugin.gd` we have: 
![image](https://github.com/codecat/godot-tbloader/assets/19198104/6e959cde-4833-47f6-a64b-4fb9cfd933b4)

@krazyjakee I see that you've done a merge request with 4.1 recently, do you know of anyway we could fix this?

**Comment by krazyjakee** [comment]
Update the cpp dependency?

**Comment by cuppajoeman** [comment]
Sorry I'm not to sure how this repository works, but I'm assuming your talking about this?
![image](https://github.com/codecat/godot-tbloader/assets/19198104/c87adcb4-a262-4eb9-8707-28eda59ec28e)

Are you implying that a possible solution would be to update that submodule and then like rebuild the project?

**Comment by codecat** [comment]
0.16.0 is out now (soon on assetlib) which resolves this.
