### ISSUE TITLE
Trenchbroom dosent work with godot 4.1

### ISSUE THREAD

**Issue by Hexadotz** [codecat/godot-tbloader#82]
I tried running it and i get an error, this plugin is my last hope so i hope you get this and just make it work with 4.1 we're not asking for new features just the ability to use it

**Comment by elvisish** [comment]
It's a shame as TBloader is a lot easier to use than Qodot, plus it's the only way to use the non-mono version of Godot to load trenchbroom maps, entity loading is easier, etc. It's a lot lighter and faster too, I just wish it was still actively maintained (I think it's feature complete anyways?)

**Comment by codecat** [comment]
Sorry for not getting back on this issue sooner. I'm happy to fix support for 4.1, but right now I'm on vacation in another continent and I am also currently sick. Soon I will fix this tho!

If someone does a PR then I can merge it even sooner of course.

**Comment by Hexadotz** [comment]
Its ok! No need to apologize or anything take all the time you need. A vacation is always needed if you code and i hope you get well soon, peace upon you my friend and again thanks for this wonderful plugin

**Comment by Cortrano** [comment]
I fixed it by adding
`compatibility_minimum = 4.1` line to _tbloader.gdextension_ file and rebuilding /bin libs by calling
`python -m SCons platform=<platform>` (tested on Windows so i typed platform=windows)

Also _godot-cpp_ submodule sould be updated to master/4.1 branch

**Comment by elvisish** [comment]
> I fixed it by adding `compatibility_minimum = 4.1` line to _tbloader.gdextension_ file and rebuilding /bin libs by calling `python -m SCons platform=<platform>` (tested on Windows so i typed platform=windows)
> 
> Also _godot-cpp_ submodule sould be updated to master/4.1 branch

Out of curiosity, why does it need updating for each new version (or each new significant version)? I'm not aware of many other plugins needing updates for version changes, unlike Unity where this standard practice (hope this doesn't come across as rude, I'm just genuinely curious and TBLoader particularly seems to need finessing through each major change).

**Comment by codecat** [comment]
0.16.0 is out now (soon on assetlib) which resolves this.
