### ISSUE TITLE
Fix GDExtension format

### ISSUE THREAD

**Issue by greenfox1505** [codecat/godot-tbloader#87]
This version of `tbloader.gdextension` allows TBLoader to be used in exports (debug and release):

```
[configuration]
entry_symbol = "tbloader_init"
compatibility_minimum = "4.1"

[libraries]
windows.release.x86_64 = "bin/tbloader.windows.x86_64.dll"
windows.debug.x86_64 = "bin/tbloader.windows.x86_64.dll"

linux.release.x86_64 = "bin/libtbloader.linux.x86_64.so"
linux.debug.x86_64 = "bin/libtbloader.linux.x86_64.so"

macos.debug.x86_64 = "bin/libtbloader.macos.universal.dylib"
macos.release.x86_64 = "bin/libtbloader.macos.universal.dylib"
```

You will also need to make sure map files are included in your build.  I could have included a "ignore autosaves" thing, but it only saves a few megs.

**Comment by codecat** [comment]
Good call, thanks! I also notice [in the godot-cpp example project](https://github.com/godotengine/godot-cpp/blob/master/test/project/example.gdextension) that libraries could be included as resources too. I wonder if that's worth looking into, as well.
