### ISSUE TITLE
Rotation `roll` should perhaps be inverted, like `pitch` is

### ISSUE THREAD

**Issue by Skaruts** [codecat/godot-tbloader#91]
It seems entities are being imported with incorrect `roll` from `angles`. I was noticing when I "rolled" entities one way in TB, they would appear rolled the opposite way in Godot. I changed this code to use `-roll` and it fixed it. So far so good.

https://github.com/codecat/godot-tbloader/blob/84a891f6499439c079833b8cf1c8335e8fec0c29/src/builder.cpp#L328-L332

I haven't tested this with `mangle`, since I have no use for it.

**Comment by codecat** [comment]
Just did some testing and you're right! I've fixed this.
