### ISSUE TITLE
gameconfig error when opening TrenchBroom

### ISSUE THREAD

**Issue by 2manydoritos** [codecat/godot-tbloader#96]
Getting this error when using the files from the tb-gameconfig folder

![Screenshot 2024-03-31 142901](https://github.com/codecat/godot-tbloader/assets/103403389/c5e2e575-952a-4e0f-97dd-68da3a60f9ad)

**Comment by shaner421** [comment]
Hi there, please try using trenchbroom version 2021.1, you are likely using the latest version of trenchbroom and the godot game configuration file will not work with the latest version.
